spring:
  application:
    name: blog

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##java
    password: 12345

  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: debug
